"""One brand file in, every themed artefact out.

A brand pack — `brand/brand.json`, or `brand/<name>/brand.json` for a named one —
is the single source of truth for colour, type and rhythm. From it this module
generates:

    .build/design/<template>/tokens.typ    Typst tokens, imported by that design
    .build/mermaid/theme/<pack>/config.json  mermaid theme variables
    .build/mermaid/theme/<pack>/style.css    mermaid stroke weights and label type

They are generated rather than hand-maintained because the alternative — the
same hex code written into a Typst file, a JSON theme and a stylesheet — drifts
the first time somebody changes one of the three. Nothing under `.build/` should
ever be edited; edit the brand pack and rebuild.
"""

from __future__ import annotations

import json
from pathlib import Path

from .config import Config

DEFAULT_BRAND = Path(__file__).resolve().parent / "brand" / "brand.json"

GENERATED = "// GENERATED by report-maker from brand/brand.json — do not edit.\n"


class BrandError(RuntimeError):
    pass


def load(cfg: Config, pack: str = "default") -> dict:
    """A brand pack, with the engine's default brand filled in underneath."""
    from . import vault  # local import: vault reads config, config knows no brands

    with DEFAULT_BRAND.open(encoding="utf-8") as handle:
        brand = json.load(handle)

    local = vault.brand_pack(cfg, pack)
    if local is not None and local.is_file():
        with local.open(encoding="utf-8") as handle:
            override = json.load(handle)
        for key, value in override.items():
            if isinstance(value, dict) and isinstance(brand.get(key), dict):
                brand[key] = {**brand[key], **value}
            else:
                brand[key] = value
    return brand


# ── Typst ────────────────────────────────────────────────────────────────────


def _typst_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _typst_value(value) -> str:
    if value is None:
        return "none"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, list):
        items = ", ".join(_typst_value(v) for v in value)
        return f"({items},)" if len(value) == 1 else f"({items})"
    if isinstance(value, dict):
        items = ", ".join(f"{k}: {_typst_value(v)}" for k, v in value.items())
        return f"({items})"
    return _typst_string(str(value))


def _typst_length(value: str) -> str:
    """`"26mm"` → `26mm`. Lengths must reach Typst unquoted."""
    text = str(value).strip()
    for unit in ("mm", "cm", "in", "pt", "em"):
        if text.endswith(unit):
            number = text[: -len(unit)]
            float(number)  # raises if the brand file is malformed
            return f"{number}{unit}"
    raise BrandError(f"{value!r} is not a length — expected e.g. \"9.8pt\" or \"26mm\"")


def _dict_block(name: str, pairs: dict[str, str]) -> str:
    body = "".join(f"  {key}: {value},\n" for key, value in pairs.items())
    return f"#let {name} = (\n{body})\n"


def tokens_typ(brand: dict) -> str:
    org = brand["org"]
    colors = {k: f'rgb("{v}")' for k, v in brand["colors"].items()}
    fonts = {k: _typst_value(v) for k, v in brand["fonts"].items()}
    sizes = {k: _typst_length(v) for k, v in brand["sizes"].items()}
    space = {k: _typst_length(v) for k, v in brand["space"].items()}
    margin = {k: _typst_length(v) for k, v in brand["page-margin"].items()}

    return "".join(
        [
            GENERATED,
            "//\n",
            f"// Brand: {org['name']}\n\n",
            _dict_block(
                "org",
                {
                    "name": _typst_value(org["name"]),
                    "url": _typst_value(org.get("url")),
                    "logo": _typst_value(org.get("logo")),
                    "logo-inverse": _typst_value(org.get("logo-inverse")),
                    "logo-width": _typst_length(org.get("logo-width", "44mm")),
                    "logo-width-header": _typst_length(
                        org.get("logo-width-header", "17mm")
                    ),
                },
            ),
            "\n",
            _dict_block("colors", colors),
            "\n",
            _dict_block("fonts", fonts),
            "\n",
            _dict_block("sizes", sizes),
            "\n",
            _dict_block("space", space),
            "\n",
            _dict_block("page-margin", margin),
            "\n",
            _dict_block(
                "defaults",
                {k: _typst_value(v) for k, v in brand.get("defaults", {}).items()},
            ),
        ]
    )


# ── mermaid ──────────────────────────────────────────────────────────────────


def mermaid_config(brand: dict) -> dict:
    c = brand["colors"]
    family = ", ".join(brand["fonts"]["text"])
    m = brand.get("mermaid", {})

    return {
        "$comment": [
            "GENERATED by report-maker from brand/brand.json — do not edit.",
            "htmlLabels MUST stay false: with HTML labels mermaid emits text inside",
            "<foreignObject>, which Typst's SVG renderer cannot draw, and the diagram",
            "arrives in the PDF as boxes with no words in them.",
        ],
        "theme": "base",
        "htmlLabels": False,
        "fontFamily": family,
        "themeVariables": {
            "fontFamily": family,
            "fontSize": m.get("font-size", "14px"),
            "background": c["surface"],
            "primaryColor": c["accent-tint"],
            "primaryBorderColor": c["accent"],
            "primaryTextColor": c["ink"],
            "secondaryColor": c["surface-alt"],
            "secondaryBorderColor": c["rule"],
            "secondaryTextColor": c["ink"],
            "tertiaryColor": c["surface"],
            "tertiaryBorderColor": c["rule-light"],
            "tertiaryTextColor": c["ink-soft"],
            "mainBkg": c["accent-tint"],
            "nodeBorder": c["accent"],
            "nodeTextColor": c["ink"],
            "lineColor": c["ink-soft"],
            "textColor": c["ink"],
            "titleColor": c["ink"],
            "edgeLabelBackground": c["surface"],
            "clusterBkg": c["surface-alt"],
            "clusterBorder": c["rule"],
            "noteBkgColor": c["surface-alt"],
            "noteBorderColor": c["rule"],
            "noteTextColor": c["ink-soft"],
            "actorBkg": c["accent-tint"],
            "actorBorder": c["accent"],
            "actorTextColor": c["ink"],
            "actorLineColor": c["rule"],
            "signalColor": c["ink-soft"],
            "signalTextColor": c["ink"],
            "labelBoxBkgColor": c["surface-alt"],
            "labelBoxBorderColor": c["rule"],
            "labelTextColor": c["ink"],
            "loopTextColor": c["ink-soft"],
            "activationBkgColor": c["accent"],
            "activationBorderColor": c["accent-deep"],
            "sequenceNumberColor": c["surface"],
            "pie1": c["accent"],
            "pie2": c["ink-soft"],
            "pie3": c["rule"],
            "pie4": c["accent-deep"],
            "pie5": c["neutral"],
            "pie6": c["rule-light"],
            "pieTitleTextColor": c["ink"],
            "pieSectionTextColor": c["surface"],
            "pieLegendTextColor": c["ink-soft"],
            "pieStrokeColor": c["surface"],
            "pieOuterStrokeColor": c["rule"],
            "taskBkgColor": c["accent-tint"],
            "taskBorderColor": c["accent"],
            "taskTextColor": c["ink"],
            "taskTextOutsideColor": c["ink-soft"],
            "activeTaskBkgColor": c["accent"],
            "activeTaskBorderColor": c["accent-deep"],
            "doneTaskBkgColor": c["surface-alt"],
            "doneTaskBorderColor": c["rule"],
            "critBkgColor": c["accent-deep"],
            "critBorderColor": c["accent-deep"],
            "gridColor": c["rule-light"],
            "sectionBkgColor": c["surface"],
            "altSectionBkgColor": c["surface-alt"],
            "todayLineColor": c["accent"],
        },
        "flowchart": {
            "htmlLabels": False,
            "curve": "basis",
            "nodeSpacing": 45,
            "rankSpacing": 55,
            "padding": 12,
            "useMaxWidth": False,
        },
        "sequence": {
            "useMaxWidth": False,
            "diagramMarginX": 12,
            "diagramMarginY": 12,
            "boxMargin": 10,
            "mirrorActors": False,
            "showSequenceNumbers": False,
        },
        "gantt": {
            "useMaxWidth": False,
            "barHeight": 18,
            "barGap": 5,
            "topPadding": 40,
            "leftPadding": 100,
            "gridLineStartPadding": 30,
        },
        "journey": {"useMaxWidth": False},
        "pie": {"useMaxWidth": False, "textPosition": 0.6},
        "er": {"useMaxWidth": False},
        "state": {"useMaxWidth": False},
        "mindmap": {"useMaxWidth": False},
        "timeline": {"useMaxWidth": False},
    }


def mermaid_css(brand: dict) -> str:
    c = brand["colors"]
    family = ", ".join(f'"{f}"' if " " in f else f for f in brand["fonts"]["text"])

    def emphasis(name: str, fill: str, stroke: str, text_fill: str, dashed=False) -> str:
        dash = "\n  stroke-dasharray: 3 3;" if dashed else ""
        return f"""
.em-{name} > rect,
.em-{name} > polygon,
.em-{name} > path,
.em-{name} > circle {{
  fill: {fill};
  stroke: {stroke};{dash}
}}
.em-{name} .nodeLabel,
.em-{name} text {{
  fill: {text_fill};
}}
"""

    return f"""/* GENERATED by report-maker from brand/brand.json — do not edit.
 *
 * config.json carries colour. This carries what themeVariables cannot reach:
 * stroke weights, label typography, and flat-not-rounded geometry. It is passed
 * to mmdc with --cssFile and applies to the rendered SVG, so it must stay to
 * properties an SVG renderer understands — no CSS variables, no calc(), no
 * webfonts (Typst rasterises the SVG and resolves fonts by name only).
 */

text,
.nodeLabel,
.edgeLabel,
.label,
.cluster-label,
.actor,
.messageText,
.loopText,
.noteText,
.taskText,
.sectionTitle,
.titleText {{
  font-family: {family};
}}

.nodeLabel,
.label {{
  font-size: 13px;
  font-weight: 400;
}}

.edgeLabel,
.edgeLabel text {{
  font-size: 11px;
  fill: {c["ink-soft"]};
}}

.cluster-label text,
.cluster-label .nodeLabel {{
  font-size: 10px;
  font-weight: 500;
  letter-spacing: 0.08em;
  fill: {c["ink-muted"]};
}}

.titleText {{
  font-size: 15px;
  fill: {c["ink"]};
}}

/* Flat corners and a hairline border, matching the boxes in the report body. */
.node rect,
.node polygon,
.node path,
.node circle,
.node ellipse {{
  stroke-width: 1.2px;
  rx: 2px;
  ry: 2px;
}}

.cluster rect {{
  stroke-width: 1px;
  stroke-dasharray: 0;
  rx: 2px;
  ry: 2px;
}}

.edgePath .path,
.flowchart-link,
line.messageLine0,
line.messageLine1 {{
  stroke-width: 1.2px;
}}

marker path {{
  stroke-width: 1px;
}}

.edgeLabel rect,
.edgeLabel .label-container {{
  fill: {c["surface"]};
  stroke: none;
}}

/* Emphasis classes. In a .mmd file: `class nodeName em-accent`, or
 * `:::em-accent` on the node. These are the only accent colours a report
 * diagram may use — everything else comes from the theme above.
 */
{emphasis("accent", c["accent"], c["accent-deep"], c["surface"])}
{emphasis("muted", c["surface-alt"], c["rule"], c["ink-soft"])}
{emphasis("good", c["positive-tint"], c["positive"], c["positive-deep"])}
{emphasis("ghost", c["surface"], c["rule"], c["ink-muted"], dashed=True)}"""


# ── sync ─────────────────────────────────────────────────────────────────────


def write_if_changed(path: Path, text: str) -> bool:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return False
    path.write_text(text, encoding="utf-8")
    return True


def mermaid_theme_dir(cfg: Config, pack: str) -> Path:
    return cfg.build / "mermaid" / "theme" / pack


def sync_mermaid(cfg: Config, pack: str = "default") -> Path:
    """Generate one pack's mermaid theme, and return the directory holding it."""
    data = load(cfg, pack)
    target = mermaid_theme_dir(cfg, pack)
    write_if_changed(target / "config.json", json.dumps(mermaid_config(data), indent=2) + "\n")
    write_if_changed(target / "style.css", mermaid_css(data))
    return target
