// The brand specimen — one document that shows every decision a brand pack makes.
//
// It is not a report and it never lives under reports/. `report-maker brand
// preview` expands the placeholders below into .build/brand-preview/<pack>/ and
// compiles it there, which is the only moment the pack being previewed is known:
// the design import has to name the staged folder that carries *that pack's*
// tokens, and a Typst import path cannot be computed at compile time.
//
// Why a document rather than a swatch sheet: a colour looks different in a
// 5mm rule on a cover than it does behind nine-point body text, and the only
// honest preview of a report design is a report. Every component the house style
// ships appears below, so a token that moves is visibly attributable to the thing
// it moved.
//
// The citation rule holds here too. Every number and colour on these pages is
// read out of the pack at render time and cited to it; everything else is marked
// as the opinion it is.

#import "{{design}}/report.typ": report
#import "{{design}}/theme.typ": org, colors, fonts, sizes, space, page-margin, label, hairline, accent-rule
#import "{{design}}/components.typ": *

#show: report.with(
  title: "Brand specimen",
  subtitle: "Every token the {{pack}} pack decides, set in the document it is for.",
  kind: "Brand specimen",
  author: org.name,
  role: "Brand pack — {{pack}}",
  date: {{date}},
  subject: "brand pack {{pack}}",
  doc-id: "BRAND-{{pack}}",
  toc: false,
  // Project-absolute, resolved against the vault root — see brandcmd.py.
  sources: "{{sources}}",
  abstract: [
    Generated by #raw("report-maker brand preview") from the pack as it stands on
    disk @preview-command. Change one value in #raw("brand.json"), run it again,
    and the difference between the two renders is that value.
  ],
)

// A font stack may be written as a list or as a single name; both reach Typst
// through the same token, so neither form may break the specimen.
#let stack-name(value) = if type(value) == str { value } else { value.first() }

// Typst normalises every length to points, so a margin written as 26mm in the
// pack would be reported back as 73.7pt. Say it the way it was written.
#let mm(value) = [#calc.round(value.mm(), digits: 1)mm]

#let swatch(name, value) = block(width: 100%, breakable: false)[
  #block(
    width: 100%,
    height: 11mm,
    fill: value,
    stroke: 0.4pt + colors.rule-light,
    radius: 2pt,
  )
  #v(3pt, weak: true)
  #text(font: fonts.mono, size: 6.2pt, fill: colors.ink)[#name]
  #linebreak()
  #text(font: fonts.mono, size: 6.2pt, fill: colors.ink-faint)[#upper(value.to-hex())]
]

= Colour, type and rhythm

#lede[
  The pack sets #colors.len() colours, #sizes.len() type sizes and #space.len()
  spacing steps @brand-pack. Nothing below is drawn from a literal — every value
  on this page is the token, so a swatch that looks wrong is a token that is
  wrong.#assess
]

#kpis(
  ([#colors.len()], [Colour tokens]),
  ([#sizes.len()], [Type sizes]),
  ([#space.len()], [Spacing steps]),
  ([#fonts.len()], [Font stacks]),
)

#source[@brand-pack]

== Colour

#srcfig(
  grid(
    columns: 6 * (1fr,),
    column-gutter: 5pt,
    row-gutter: 9pt,
    ..colors.pairs().map(pair => swatch(pair.at(0), pair.at(1))),
  ),
  kind: image,
  caption: [
    Every colour the pack decides, named as a design refers to it. The strip is
    generated from the dictionary itself, so a colour that exists is drawn.
  ],
  source: [@brand-pack],
)

=== Where each family is used

#keyvalues((
  ([accent], [Cover band, heading numbers, citation markers, list bullets, the left rule on findings and callouts @components.]),
  ([ink], [Body text and headings; the soft, muted and faint steps carry captions, labels and running chrome @components.]),
  ([rule], [Hairlines under headings, table rules and figure frames @components.]),
  ([surface], [Page and the washed background behind callouts, code and the verdict block @components.]),
  ([positive], [The one non-accent signal colour: strengths, and a passing score in the scorecard @components.]),
))

== Type

#srcfig(
  table(
    columns: (auto, auto, 1fr),
    align: (left + horizon, right + horizon, left + horizon),
    table.header([Token], [Size], [Specimen]),
    ..sizes
      .pairs()
      .map(pair => (
        text(font: fonts.mono, size: 7.6pt)[#("sizes." + pair.at(0))],
        text(font: fonts.mono, size: 7.6pt, fill: colors.ink-faint)[#pair.at(1)],
        text(
          font: if pair.at(0).starts-with("cover") or pair.at(0).starts-with("h") {
            fonts.display
          } else {
            fonts.text
          },
          size: pair.at(1),
        )[Hamburgefonstiv],
      ))
      .flatten(),
  ),
  caption: [The type scale, each row set at its own size in the face that uses it.],
  source: [@brand-pack],
)

#keyvalues((
  ([fonts.display], [#text(font: fonts.display, size: 12pt)[#stack-name(fonts.display) — headings, covers and quotations]]),
  ([fonts.text], [#text(font: fonts.text, size: 10pt)[#stack-name(fonts.text) — body copy, tables and labels]]),
  ([fonts.mono], [#text(font: fonts.mono, size: 9pt)[#stack-name(fonts.mono) — code, identifiers and figures]]),
))

Body copy is set in the text stack at #sizes.body @brand-pack. This paragraph
exists to be read at length rather than sampled: justification, leading, the
colour of a #link("https://example.com")[link], `inline code`, and the way a
citation marker @engine-brand sits in a line of prose are all decisions the pack
makes, and none of them can be judged from a swatch.#assess

== Rhythm

#srcfig(
  grid(
    columns: (auto, auto, 1fr),
    column-gutter: 9pt,
    row-gutter: 5pt,
    ..space
      .pairs()
      .map(pair => (
        text(font: fonts.mono, size: 7.6pt)[#("space." + pair.at(0))],
        text(font: fonts.mono, size: 7.6pt, fill: colors.ink-faint)[#pair.at(1)],
        box(rect(width: pair.at(1), height: 5pt, fill: colors.accent, radius: 1pt)),
      ))
      .flatten(),
  ),
  kind: image,
  caption: [
    The spacing steps, drawn at their own length. Page margins are #mm(page-margin.top)
    top, #mm(page-margin.bottom) bottom and #mm(page-margin.x) on each side.
  ],
  source: [@brand-pack],
)

= Components

#lede[
  The same tokens, assembled into the pieces a report is actually built from. A
  pack that reads well as a swatch strip and badly here is a pack that reads
  badly.#assess
]

== Callouts

#grid(
  columns: (1fr, 1fr),
  column-gutter: 7pt,
  row-gutter: 7pt,
  callout(kind: "note")[
    The neutral kind. It takes the faint ink and the washed surface, so it sits
    behind the text rather than in front of it.#assess
  ],
  callout(kind: "insight")[
    Accent on the accent tint. This is the loudest thing on a body page, which is
    why there should be one of them.#assess
  ],
  callout(kind: "risk")[
    The deep accent. It has to read as a warning without a second signal colour
    being introduced to the palette.#assess
  ],
  callout(kind: "caution")[
    Accent on the plain surface — a half-step down from risk, for a caveat that
    is not yet a finding.#assess
  ],
  callout(kind: "strength")[
    The one place the positive colour appears in prose, so it keeps its
    meaning.#assess
  ],
  callout(kind: "method")[
    Neutral ink, for how the evidence was gathered and what its limits are.#assess
  ],
)

#assessment[
  The seventh kind is this one. Anything longer than a sentence or two of our own
  judgement belongs in an assessment block rather than in a trail of #assess
  markers, and it is deliberately the plainest block in the set: an opinion should
  not be dressed as evidence.
]

== Findings and judgement

#finding(
  id: "S-01",
  title: "Every colour token reaches this page",
  severity: "high",
  area: "Brand",
  confidence: "High",
  evidence: [
    The swatch strip above is generated from the pack's #raw("colors") dictionary
    rather than from a fixed list, so a token that exists is drawn @brand-pack.
  ],
  impact: [A value edited in #raw("brand.json") is visible here before it reaches a report.#assess],
  action: [Re-run #raw("report-maker brand preview") after every edit, and read the strip.#assess],
)

#srcfig(
  scorecard((
    ("Contrast", 4, 5, "Ink against surface, at body size."),
    ("Distinctiveness", 3, 5, "How far the accent sits from the defaults."),
    ("Range", 4, 5, "Enough steps of ink and rule to build a page."),
    ("Restraint", 2, 5, "How many colours carry meaning at once."),
  )),
  caption: [
    A scorecard, drawn so its bars and rules can be judged. The ratings are
    placeholders in a specimen, not an assessment of this pack.#assess
  ],
  source: [none — assessment, not evidence],
)

#verdict(
  [The pack is legible at body size and coherent across the components.],
  [Read the page, not the palette: a colour that survives a swatch strip can still
  fail behind nine-point text.#assess],
  tone: "caution",
)

== Quotation and claim

#claim(
  [Design tokens live in a brand pack and nowhere else — no hex code is ever
  written into a Typst or mermaid file.],
  attribution: "report-maker, repository instructions",
  source: [@components],
)

#srcquote(
  "Everything here is built from the brand tokens, so a document assembled from these pieces looks like it came from the same house as every other one.",
  attribution: "report-maker engine",
  source: [@components],
  locator: "components.typ, header comment",
)

Both blocks set the words in the display face behind an accent rule, and both
carry their provenance in the same faint micro type @components. They are the
only places a report reproduces someone else's words, so they are deliberately
hard to confuse with our own prose.#assess
